version: '3.3'

services:

  portainer:
    image: portainer/portainer
    ports:
      - '9000:9000'
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - apache
      - db
      - phpmyadmin

  apache:
    depends_on:
      - db
    build: .
    image: php:5
    restart: always
    volumes:
      - ./web:/usr/src/myapp
    ports:
      - 80:80
    networks:
      - net

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - net

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - net

networks:
  net:

volumes:
  db_data: